name: Sync Changes to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Configure Git
    - name: Configure Git for PythonAnywhere
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    # Step 3: Push Changes to PythonAnywhere
    - name: Push changes to PythonAnywhere
      env:
        #PA_USER: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://{{ secrets.GITHUB_PAT }}@github.com/akshay56789/Komyuniti---SNS---prod.git
        git pull origin main --no-edit
        git push origin main

