name: Sync Changes to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  update-pythonanywhere:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SSHPass
        run: sudo apt-get install -y sshpass

      - name: Update PythonAnywhere Files via HTTPS
        env:
          PYTHONANYWHERE_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          PYTHONANYWHERE_PASSWORD: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
          GITHUB_PAT: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Pulling changes on PythonAnywhere"
          sshpass -p "$PYTHONANYWHERE_PASSWORD" ssh -o StrictHostKeyChecking=no "$PYTHONANYWHERE_USERNAME@ssh.pythonanywhere.com" "
            cd /home/$PYTHONANYWHERE_USERNAME/Komyuniti &&
            git remote set-url origin https://$GITHUB_PAT@github.com/akshay56789/Komyuniti---SNS---prod.git &&
            git pull origin main
          "
