name: Sync Changes to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  update-pythonanywhere:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Sync Changes Using PythonAnywhere API
        env:
          PYTHONANYWHERE_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          PYTHONANYWHERE_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
          GITHUB_PAT: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Triggering update via PythonAnywhere API"
          curl -X POST https://www.pythonanywhere.com/api/v0/user/$PYTHONANYWHERE_USERNAME/files/path/home/$PYTHONANYWHERE_USERNAME/Komyuniti/ \
          -H "Authorization: Token $PYTHONANYWHERE_API_TOKEN" \
          -d "command=cd /home/$PYTHONANYWHERE_USERNAME/Komyuniti && git pull https://$GITHUB_PAT@github.com/akshay56789/Komyuniti---SNS---prod.git main --no-edit"
