name: Sync Changes to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  update-pythonanywhere:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update PythonAnywhere Files via HTTPS
        env:
          PYTHONANYWHERE_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          PYTHONANYWHERE_PASSWORD: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
          GITHUB_PAT: ${{ secrets.GH_TOKEN}}
        run: |
          echo "Syncing changes to PythonAnywhere via HTTPS"

          curl -u $PYTHONANYWHERE_USERNAME:$PYTHONANYWHERE_PASSWORD ssh.pythonanywhere.com <<EOF
          cd /home/$PYTHONANYWHERE_USERNAME/your_project_directory &&
          git pull https://$GITHUB_PAT@github.com/akshay56789/Komyuniti---SNS---prod.git main --no-edit
          EOF

