name: Sync Changes to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code from GitHub
      uses: actions/checkout@v3

    - name: Set up Git for PythonAnywhere
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Sync Changes to PythonAnywhere
      env:
        PYTHONANYWHERE_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        PYTHONANYWHERE_PASSWORD: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
      run: |
        sshpass -p "${{ secrets.PYTHONANYWHERE_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com" "
        cd /home/${{ secrets.PYTHONANYWHERE_USERNAME }}/Komyuniti &&
        git pull origin main
        "

