name: Sync Changes to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code from GitHub
      uses: actions/checkout@v3

    - name: Set up Git for PythonAnywhere
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Sync Changes to PythonAnywhere
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        # Log into PythonAnywhere (ensure you have your username and password or token)
        sshpass -p ${{ secrets.PYTHONANYWHERE_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com "
          cd /path/to/your/webapp && git pull origin main
        "
